name: C++ Build with CMake and vcpkg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ cmake
          sudo apt-get install nasm

      - name: Cmake Version
        run: |
          cmake --version

      - name: Configure CMake
        run: |
          cmake -B cmake-build-release-linux

      - name: Build
        run: cmake --build cmake-build-release-linux --config Release -- -j 12

      - name: Copy Additional Files
        run: cp ./ggml-metal.metal cmake-build-release-linux

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cmake-build-release-ubuntu-latest
          path: cmake-build-release-linux/
      
      - name: Archive Build binary Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: whisper-cpp-server-ubuntu-latest
          path: |
            cmake-build-release-linux/ggml-metal.metal
            cmake-build-release-linux/simplest
            cmake-build-release-linux/whisper_http_server_base_httplib
            cmake-build-release-linux/whisper_server_base_on_uwebsockets
            cmake-build-release-linux/thirdparty/whisper.cpp/libwhisper.so
  

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install Dependencies
        run: |
          brew install cmake
          brew install nasm

      - name: Cmake Version
        run: |
          cmake --version

      - name: Setup vcpkg
        run: |
          export VCPKG_HOME=$PWD/thirdparty/vcpkg
          echo $VCPKG_HOME 
          $VCPKG_HOME/bootstrap-vcpkg.sh

      - name: Configure CMake
        run: |
          export VCPKG_HOME=$PWD/thirdparty/vcpkg
          cmake -B cmake-build-release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_HOME/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build cmake-build-release --config Release -- -j

      - name: Copy Additional Files
        run: cp ./ggml-metal.metal cmake-build-release

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cmake-build-release-macos-latest
          path: cmake-build-release/
